# Implement Gradient Descent For Neural Network (or Logistic Regression)
#### Predicting if a person have heart disease or not  using logistic regression
Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person have disease or he/she doesn't).

DataSource: https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('F:\AAA Machine Learning\Kaggle\heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

# Preprocessing Data

### age

In [3]:
df['age'].describe()

count    1025.000000
mean       54.434146
std         9.072290
min        29.000000
25%        48.000000
50%        56.000000
75%        61.000000
max        77.000000
Name: age, dtype: float64

In [4]:
df['age'] = df['age']/100

### sex

In [5]:
df['sex'].value_counts()

1    713
0    312
Name: sex, dtype: int64

### cp

In [6]:
df['cp'].value_counts()

0    497
2    284
1    167
3     77
Name: cp, dtype: int64

In [7]:
df = pd.get_dummies(df,columns=['cp'],drop_first=True,dtype=int)

### trestbps

In [8]:
df['trestbps'].describe()

count    1025.000000
mean      131.611707
std        17.516718
min        94.000000
25%       120.000000
50%       130.000000
75%       140.000000
max       200.000000
Name: trestbps, dtype: float64

In [9]:
df['trestbps'] = df['trestbps'] / 200

### chol

In [10]:
df['chol'].describe()

count    1025.00000
mean      246.00000
std        51.59251
min       126.00000
25%       211.00000
50%       240.00000
75%       275.00000
max       564.00000
Name: chol, dtype: float64

In [11]:
df['chol'] = df['chol']/500

### fbs

In [12]:
df['fbs'].value_counts()

0    872
1    153
Name: fbs, dtype: int64

### restecg

In [13]:
df['restecg'].describe()

count    1025.000000
mean        0.529756
std         0.527878
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: restecg, dtype: float64

In [14]:
df['restecg'] = np.where(df['restecg']==2,np.mean(df['restecg']),df['restecg'])

### thalach

In [15]:
df['thalach'].describe()

count    1025.000000
mean      149.114146
std        23.005724
min        71.000000
25%       132.000000
50%       152.000000
75%       166.000000
max       202.000000
Name: thalach, dtype: float64

In [16]:
df['thalach'] = df['thalach'] / 150

### exang

In [17]:
df['exang'].value_counts()

0    680
1    345
Name: exang, dtype: int64

### oldpeak

In [18]:
df['oldpeak'].describe()

count    1025.000000
mean        1.071512
std         1.175053
min         0.000000
25%         0.000000
50%         0.800000
75%         1.800000
max         6.200000
Name: oldpeak, dtype: float64

In [19]:
# import scipy.stats
# plt.figure(figsize=(20,10))
# plt.subplot(1,2,1)
# sns.distplot(df['oldpeak'],kde=True,fit = scipy.stats.norm)
# plt.title("With Out Log Transform")
# plt.subplot(1,2,2)
# sns.distplot(np.log(df['oldpeak']),kde=True,fit = scipy.stats.norm)
# plt.xlabel('Log Old Peak')
# plt.title("With Log Transform")

# plt.show()

### target

In [20]:
df['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

# Split train and test set

In [21]:
from sklearn.model_selection import train_test_split
y = df['target']
X = df.drop(['target'],axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
print(X_train.shape)
print(X_test.shape)

(820, 15)
(205, 15)


In [24]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(15,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10)


Epoch 1/10
26/26 [==============================] - 1s 6ms/step - loss: 5.4236 - accuracy: 0.5159
Epoch 2/10
26/26 [==============================] - 0s 6ms/step - loss: 5.2718 - accuracy: 0.5159
Epoch 3/10
26/26 [==============================] - 0s 6ms/step - loss: 5.1200 - accuracy: 0.5159
Epoch 4/10
26/26 [==============================] - 0s 7ms/step - loss: 4.9697 - accuracy: 0.5159
Epoch 5/10
26/26 [==============================] - 0s 6ms/step - loss: 4.8198 - accuracy: 0.5159
Epoch 6/10
26/26 [==============================] - 0s 7ms/step - loss: 4.6703 - accuracy: 0.5159
Epoch 7/10
26/26 [==============================] - 0s 7ms/step - loss: 4.5201 - accuracy: 0.5159
Epoch 8/10
26/26 [==============================] - 0s 7ms/step - loss: 4.3697 - accuracy: 0.5159
Epoch 9/10
26/26 [==============================] - 0s 7ms/step - loss: 4.2199 - accuracy: 0.5159
Epoch 10/10
26/26 [==============================] - 0s 10ms/step - loss: 4.0692 - accuracy: 0.5159


In [64]:
model.evaluate(X_test,y_test)

7/7 [==============================] - 0s 2ms/step - loss: 0.4267 - accuracy: 0.8195


[0.4267168641090393, 0.8195121884346008]

In [65]:
X_test.head()

age  sex  trestbps   chol  fbs  restecg   thalach  exang  oldpeak  \
527  0.62    0      0.62  0.418    0      1.0  1.086667      0      0.0   
359  0.53    0      0.64  0.432    0      0.0  0.766667      0      0.0   
447  0.55    1      0.80  0.578    0      0.0  0.966667      1      0.8   
31   0.50    0      0.60  0.488    0      1.0  1.080000      0      1.1   
621  0.48    1      0.65  0.512    1      0.0  1.000000      1      0.0   

     slope  ca  thal  cp_1  cp_2  cp_3  
527      2   0     2     0     0     0  
359      2   0     0     0     1     0  
447      1   1     3     0     0     0  
31       2   0     2     1     0     0  
621      2   2     3     0     0     0

In [66]:
model.predict(X_test)

7/7 [==============================] - 0s 2ms/step


array([[9.39300179e-01],
       [9.95315731e-01],
       [3.26115042e-02],
       [9.68322039e-01],
       [4.12542932e-02],
       [7.58630931e-01],
       [9.69398674e-03],
       [4.68910765e-03],
       [8.24636877e-01],
       [1.93881914e-02],
       [9.74190176e-01],
       [6.62504463e-03],
       [9.31090355e-01],
       [8.16683710e-01],
       [6.81881160e-02],
       [9.14428234e-01],
       [1.01779895e-02],
       [9.64008152e-01],
       [8.47513914e-01],
       [1.34697584e-02],
       [7.61544466e-01],
       [7.58575425e-02],
       [5.97395420e-01],
       [7.95095507e-03],
       [7.61544466e-01],
       [5.88050604e-01],
       [9.81856763e-01],
       [5.47898173e-01],
       [7.45722232e-03],
       [8.89633179e-01],
       [6.71816289e-01],
       [8.70402277e-01],
       [4.84958410e-01],
       [9.95315731e-01],
       [8.27758729e-01],
       [7.94207573e-01],
       [7.61544466e-01],
       [3.98583323e-01],
       [6.43455446e-01],
       [9.49219584e-01],


In [67]:
y_test

527    1
359    1
447    0
31     1
621    0
      ..
832    1
796    1
644    1
404    0
842    0
Name: target, Length: 205, dtype: int64

In [68]:
coef,intercepts = model.get_weights()
coef,intercepts

(array([[ 0.15688989],
        [-1.345855  ],
        [-0.24782217],
        [-1.1895176 ],
        [-0.30132228],
        [ 0.46258244],
        [ 2.6813254 ],
        [-0.7926838 ],
        [-0.60304916],
        [ 0.67638546],
        [-0.80751455],
        [-0.9939978 ],
        [ 1.4591132 ],
        [ 1.9879893 ],
        [ 2.245601  ]], dtype=float32),
 array([0.5517272], dtype=float32))