In [59]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [60]:
# Loading the iris dataset
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [61]:
# Type of the iris
type(iris)

sklearn.utils.Bunch

In [62]:
# Convert into dataframe

import pandas as pd

df = pd.DataFrame(data = iris.data,columns=iris.feature_names)
df['target'] = iris.target

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [63]:
# size of dataframe
print(df.shape)

(150, 5)


In [64]:
df['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [69]:
# train test split 

from sklearn.model_selection import train_test_split
X = df.iloc[:,2:4]
y = (df['target']==0).astype(np.int)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_15816/1256984716.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = (df['target']==0).astype(np.int)


In [70]:
X.head()

petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
2                1.3               0.2
3                1.5               0.2
4                1.4               0.2

In [71]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int32

In [72]:
#X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [73]:
# model
per_clf = Perceptron()
per_clf.fit(X,y)

Perceptron()

In [74]:
per_clf.coef_

array([[-0.7, -1.2]])

In [75]:
per_clf.get_params()

{'alpha': 0.0001,
 'class_weight': None,
 'early_stopping': False,
 'eta0': 1.0,
 'fit_intercept': True,
 'l1_ratio': 0.15,
 'max_iter': 1000,
 'n_iter_no_change': 5,
 'n_jobs': None,
 'penalty': None,
 'random_state': 0,
 'shuffle': True,
 'tol': 0.001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [76]:
y_pred = per_clf.predict([[2,0.5]])

Note that contrary to Logistic Regression classifiers, Perceptrons do not
output a class probability; rather, they make predictions based on a hard
threshold. This is one reason to prefer Logistic Regression over
Perceptrons.

In [78]:
y_pred[0]

0

In [90]:
X_OR = {
    'x1':[0,0,1],
    'x2':[0,1,0],
    'output':[0,1,1]
}

In [91]:
df1 = pd.DataFrame.from_dict(X_OR)

In [92]:
df1.head()

x1  x2  output
0   0   0       0
1   0   1       1
2   1   0       1

In [93]:
X = df1.iloc[:,0:2]
y = df1['output']

In [94]:
X

x1  x2
0   0   0
1   0   1
2   1   0

In [95]:
y

0    0
1    1
2    1
Name: output, dtype: int64

In [96]:
per_clf.fit(X,y)

Perceptron()

In [97]:
per_clf.coef_

array([[2., 2.]])

In [99]:
per_clf.predict([[1,1]])

array([1], dtype=int64)

In [100]:
per_clf.predict([[0,1]])

array([1], dtype=int64)